coverage:
  status:
    project:
      default:
        threshold: 85%
    patch:
      default:
        threshold: 85%

fixes:
  - "/home/runner/work/metabot-experiment/metabot-experiment/coverage/::coverage/"